version: '3.8'

services:
  backend:
    image: store-backend:latest
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    image: store-frontend:latest
    build:
      context: ./frontend
    ports:
      - "4200:80"
